apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-github-username/your-repo-name'
    targetRevision: HEAD
    path: charts/abb  # Path to your Helm chart in the repo
    helm:
      valueFiles:
        - values.yaml  
  destination:
    server: 'https://abb.azuredns.net'  # Point to the AKS cluster
    namespace: default  # Kubernetes namespace where the app will be deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # Automatically create the namespace if it doesn't exist
