name: Deploy to AKS with Argo CD

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/setup-azure@v1
        with:
          azure-cli-version: '2.33.0'  

      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group my-aks-resource-group --name my-aks-cluster --overwrite-existing

      - name: Install kubectl
        run: |
          az aks install-cli

      - name: Install Argo CD CLI
        run: |
          curl -SSL https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 -o argocd
          sudo install argocd /usr/local/bin

      - name: Apply Argo CD Application
        run: kubectl apply -f argocd-app.yaml

      - name: Sync Argo CD Application
        run: argocd app sync my-argocd-app
